---
name: test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        entry:
          - { ruby: 3.4 }
    name: test (ruby=${{ matrix.entry.ruby }})
    steps:
      - uses: actions/checkout@v5
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.entry.ruby }}
          bundler-cache: true
      - name: Run Tests
        run: bundle exec rake
